### ISSUE TITLE
Belt Sorter collides with built-in Factorio `log` function in global namespace

### ISSUE THREAD

**Issue by Afforess** [judos/beltSorter#14] opened 2016-09-19 00:30 UTC
@judos  It seems your logging library, loaded at data-load-time in Factorio, is replacing the built-in global `log` function, which prints to the factorio-current.log file. The offending code seems to be this line: https://github.com/judos/beltSorter/blob/master/source/libs/logging.lua#L1

It breaks a number of mods, such as Bob's mods and Marathon, and countless others.

I see no other solution here but to tell you not to assign `log` as a function/variable in data-load-time. The lua runtime while Factorio is loading is shared, and this is causing belt sorter to conflict with many other mods. You need to pick a different variable name.

**Comment by judos** [comment] 2016-09-19 07:13
Ups, now that's unfortunate. Thanks for the hint. I will correct it asap.

**Comment by coderatchet** [comment] 2016-09-19 10:18
The problem is a reassignment of the global log variable in the first line of logging.lua . use a local variable or name the log something else.

**Comment by cnmcavoy** [comment] 2016-09-19 14:29
I talked with rseding on the #factorio irc channel and re-assigning factorio built-ins during the data phase may become an error that prevents from the game from starting in newer releases, to prevent this sort of problem.

**Comment by Lappro** [comment] 2016-09-19 21:21
Added a pull request that should fix this, but here is a hot fix to get you going in the mean time: https://github.com/Lappro/beltSorter/raw/master/release/beltSorter_0.3.2.zip

**Comment by judos** [comment] 2016-09-19 22:18
Closed already with the pull request @Lappro, thanks for contributing!

**Closed by judos** 2016-09-19 22:18 UTC
