### ISSUE TITLE
Basic belt sorter works unpowered

### ISSUE THREAD

**Issue by Jelmergu** [judos/beltSorter#27] opened 2018-01-21 19:18 UTC
When a basic belt sorter is in a the area of effect of a unpowered pole it works

What did I do:
1 place basic belt sorter
2 set it up
3 place a wooden power pole close enough to the sorter but not to any powered pole

The unpowered icon stays on the sorter, but the sorter did start sorting

**Comment by judos** [comment] 2019-06-27 23:14
Could not reproduce, tried this setup:
![grafik](https://user-images.githubusercontent.com/5525810/60306799-0b6b8d80-9942-11e9-8842-8211f2c1d4cc.png)

Seems fixed on factorio 0.17.52.

**Closed by judos** 2019-06-27 23:14 UTC
Labels: bug
